//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace astorWorkMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int UserRoleID { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public int Status { get; set; }
        public string UserLanguage { get; set; }
        public string UserCulture { get; set; }
        public string UserTheme { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<System.DateTime> PasswordExpiryDate { get; set; }
        public Nullable<int> DefaultModuleID { get; set; }
    }
}
