//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace astorWorkDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneMapping
    {
        public int AstorWorkZoneID { get; set; }
        public int AstorSafeZoneID { get; set; }
        public int AstorTrackZoneID { get; set; }
        public string ZoneName { get; set; }
    }
}
