//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace astorWorkMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationAssociation
    {
        public int AssociationID { get; set; }
        public string ParentType { get; set; }
        public int ParentID { get; set; }
        public string AssociationType { get; set; }
        public string ChildType { get; set; }
        public int ChildID { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string RFIDTagID { get; set; }
    }
}
