//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRDbUpdates.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ConfigurationMaster
    {
        [Key]
        public string Configuration { get; set; }
        public string Setting { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
    }
}
