//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRDbUpdates.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class astorTrack_GEEntities : DbContext
    {
        public astorTrack_GEEntities()
            : base("name=astorTrack_GEEntities")
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
    
        public virtual DbSet<ConfigurationMaster> ConfigurationMasters { get; set; }
        public virtual DbSet<MaterialDetail> MaterialDetails { get; set; }
        public virtual DbSet<MaterialMaster> MaterialMaster { get; set; }
        public virtual DbSet<Beacon> Beacons { get; set; }
    }
}
