//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackfest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CUSTOM_VISION_TRAINING_KEY {
            get {
                return ((string)(this["CUSTOM_VISION_TRAINING_KEY"]));
            }
            set {
                this["CUSTOM_VISION_TRAINING_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CUSTOM_VISION_PROJECT_ID {
            get {
                return ((string)(this["CUSTOM_VISION_PROJECT_ID"]));
            }
            set {
                this["CUSTOM_VISION_PROJECT_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CUSTOM_VISION_PREDICTION_KEY {
            get {
                return ((string)(this["CUSTOM_VISION_PREDICTION_KEY"]));
            }
            set {
                this["CUSTOM_VISION_PREDICTION_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CAMERA_UUID {
            get {
                return ((string)(this["CAMERA_UUID"]));
            }
            set {
                this["CAMERA_UUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CAMERA_RESOLUTION_WIDTH {
            get {
                return ((int)(this["CAMERA_RESOLUTION_WIDTH"]));
            }
            set {
                this["CAMERA_RESOLUTION_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CAMERA_RESOLUTION_HEIGHT {
            get {
                return ((int)(this["CAMERA_RESOLUTION_HEIGHT"]));
            }
            set {
                this["CAMERA_RESOLUTION_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FACE_API_PROJECT_ID {
            get {
                return ((string)(this["FACE_API_PROJECT_ID"]));
            }
            set {
                this["FACE_API_PROJECT_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FACE_API_PRIMARY_KEY {
            get {
                return ((string)(this["FACE_API_PRIMARY_KEY"]));
            }
            set {
                this["FACE_API_PRIMARY_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FACE_API_SECONDARY_KEY {
            get {
                return ((string)(this["FACE_API_SECONDARY_KEY"]));
            }
            set {
                this["FACE_API_SECONDARY_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double FACE_API_THRESHHOLD {
            get {
                return ((double)(this["FACE_API_THRESHHOLD"]));
            }
            set {
                this["FACE_API_THRESHHOLD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public double CUSTOM_VISION_SAFE_THRESHOLD {
            get {
                return ((double)(this["CUSTOM_VISION_SAFE_THRESHOLD"]));
            }
            set {
                this["CUSTOM_VISION_SAFE_THRESHOLD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double CUSTOM_VISION_UNSAFE_THRESHOLD {
            get {
                return ((double)(this["CUSTOM_VISION_UNSAFE_THRESHOLD"]));
            }
            set {
                this["CUSTOM_VISION_UNSAFE_THRESHOLD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SAFETY_CHECK_INTERVAL {
            get {
                return ((int)(this["SAFETY_CHECK_INTERVAL"]));
            }
            set {
                this["SAFETY_CHECK_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("southeastasia.api.cognitive.microsoft.com")]
        public string FACE_API_ENDPOINT {
            get {
                return ((string)(this["FACE_API_ENDPOINT"]));
            }
            set {
                this["FACE_API_ENDPOINT"] = value;
            }
        }
    }
}
