apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: apigateway
  namespace: prod
  labels:
    app: apigateway
spec:
  replicas: 5
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: astorwork
        image: astorwork.azurecr.io/api-gateway-2019:1006
        env:
        - name: TENANT_INFO_TBL
          value: TenantInfoProd
        - name: AW_REDIS_CACHE_CONNECTION
          value: astorworkProd.redis.cache.windows.net:6380,password=NgCdNUSdyraWS1GL19C6MRVaAlyM9115iAlkd0z9c+c=,ssl=True,abortConnect=False
        - name: IMAGE_CONTAINER
          value: prod-tenant-repo
                  
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: extensions/v1beta1
kind: Service
apiVersion: v1
metadata:
  name: apigateway
  namespace: prod
spec:
  selector:
    app: apigateway
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443