//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace astorWorkNavis2017.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ACCESS_TOKEN {
            get {
                return ((string)(this["ACCESS_TOKEN"]));
            }
            set {
                this["ACCESS_TOKEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string REFRESH_TOKEN {
            get {
                return ((string)(this["REFRESH_TOKEN"]));
            }
            set {
                this["REFRESH_TOKEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PROJECT_ID {
            get {
                return ((int)(this["PROJECT_ID"]));
            }
            set {
                this["PROJECT_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1970-01-01 +08:00")]
        public global::System.DateTimeOffset LAST_SYNC_TIME {
            get {
                return ((global::System.DateTimeOffset)(this["LAST_SYNC_TIME"]));
            }
            set {
                this["LAST_SYNC_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1970-01-01 +08:00")]
        public global::System.DateTimeOffset ACCESS_TOKEN_EXPIRES {
            get {
                return ((global::System.DateTimeOffset)(this["ACCESS_TOKEN_EXPIRES"]));
            }
            set {
                this["ACCESS_TOKEN_EXPIRES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LAST_SYNC_ID {
            get {
                return ((int)(this["LAST_SYNC_ID"]));
            }
            set {
                this["LAST_SYNC_ID"] = value;
            }
        }
    }
}
