//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace astorWorkMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialMasterMarkingNo
    {
        public long ID { get; set; }
        public string MarkingNo { get; set; }
        public string MaterialType { get; set; }
        public Nullable<int> LotNo { get; set; }
        public Nullable<System.DateTime> CastingDate { get; set; }
        public string RFIDTagID { get; set; }
        public string BeaconID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string MaterialNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Project { get; set; }
    }
}
