//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Add Materials.
        /// </summary>
        internal static string AddMaterials {
            get {
                return ResourceManager.GetString("AddMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOM Material Created Successfully.
        /// </summary>
        internal static string BOMCreated {
            get {
                return ResourceManager.GetString("BOMCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOM Material Deleted Successfully.
        /// </summary>
        internal static string BOMMaterialDeleted {
            get {
                return ResourceManager.GetString("BOMMaterialDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOM Material Updated Successfully.
        /// </summary>
        internal static string BOMUpdated {
            get {
                return ResourceManager.GetString("BOMUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Name Already Exists.
        /// </summary>
        internal static string CertificatesNameExists {
            get {
                return ResourceManager.GetString("CertificatesNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name Already Exists.
        /// </summary>
        internal static string CompanyNameExists {
            get {
                return ResourceManager.GetString("CompanyNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected CS is already linked with this CS..
        /// </summary>
        internal static string ConnectingCSExists {
            get {
                return ResourceManager.GetString("ConnectingCSExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected location is already linked with this location..
        /// </summary>
        internal static string ConnectingLocationExists {
            get {
                return ResourceManager.GetString("ConnectingLocationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected yard is already linked with this yard..
        /// </summary>
        internal static string ConnectingYardExists {
            get {
                return ResourceManager.GetString("ConnectingYardExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name Already Exists.
        /// </summary>
        internal static string DepartmentNameExists {
            get {
                return ResourceManager.GetString("DepartmentNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected device is already allocated..
        /// </summary>
        internal static string DeviceAllocated {
            get {
                return ResourceManager.GetString("DeviceAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove any devices allocated to gangway before changing location.
        /// </summary>
        internal static string DeviceConnected {
            get {
                return ResourceManager.GetString("DeviceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device IP Address Already Exists.
        /// </summary>
        internal static string DeviceIPAddressExists {
            get {
                return ResourceManager.GetString("DeviceIPAddressExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device MAC Address Already Exists.
        /// </summary>
        internal static string DeviceMACAddressExists {
            get {
                return ResourceManager.GetString("DeviceMACAddressExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name Already Exists.
        /// </summary>
        internal static string DeviceNameExists {
            get {
                return ResourceManager.GetString("DeviceNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Serial No Already Exists.
        /// </summary>
        internal static string DeviceSerialNoExists {
            get {
                return ResourceManager.GetString("DeviceSerialNoExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Already Exists.
        /// </summary>
        internal static string EmpCertificationDetailsExists {
            get {
                return ResourceManager.GetString("EmpCertificationDetailsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee already has an active Tag, cannot add another one.
        /// </summary>
        internal static string EmpHasActiveRFIDTag {
            get {
                return ResourceManager.GetString("EmpHasActiveRFIDTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gangway Name Already Exists.
        /// </summary>
        internal static string GangwayNameExists {
            get {
                return ResourceManager.GetString("GangwayNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRN Created Sucessfully.
        /// </summary>
        internal static string GRNCreated {
            get {
                return ResourceManager.GetString("GRNCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one mobile app module.
        /// </summary>
        internal static string HandheldModule {
            get {
                return ResourceManager.GetString("HandheldModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Failed.
        /// </summary>
        internal static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee FIN/NRIC No  Already Exists.
        /// </summary>
        internal static string IsEmployeeFINNRICNoExists {
            get {
                return ResourceManager.GetString("IsEmployeeFINNRICNoExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID Already Exists.
        /// </summary>
        internal static string IsEmployeeIDExists {
            get {
                return ResourceManager.GetString("IsEmployeeIDExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Created Successfully.
        /// </summary>
        internal static string JobCreated {
            get {
                return ResourceManager.GetString("JobCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobNo Created Successfully.
        /// </summary>
        internal static string JobNoCreated {
            get {
                return ResourceManager.GetString("JobNoCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobNo Updated Successfully.
        /// </summary>
        internal static string JobNoUpdated {
            get {
                return ResourceManager.GetString("JobNoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Number Already Exists.
        /// </summary>
        internal static string JobNumberExists {
            get {
                return ResourceManager.GetString("JobNumberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Updated Successfully.
        /// </summary>
        internal static string JobUpdated {
            get {
                return ResourceManager.GetString("JobUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading records.
        /// </summary>
        internal static string LoadingError {
            get {
                return ResourceManager.GetString("LoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Association Created Successfully.
        /// </summary>
        internal static string LocationAssocCreated {
            get {
                return ResourceManager.GetString("LocationAssocCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Association Updated Successfully.
        /// </summary>
        internal static string LocationAssocUpdated {
            get {
                return ResourceManager.GetString("LocationAssocUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Already Exists.
        /// </summary>
        internal static string LocationCodeExists {
            get {
                return ResourceManager.GetString("LocationCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Created Sucessfully.
        /// </summary>
        internal static string LocationCreated {
            get {
                return ResourceManager.GetString("LocationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Updated Sucessfully.
        /// </summary>
        internal static string LocationUpdated {
            get {
                return ResourceManager.GetString("LocationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Code Already Exists.
        /// </summary>
        internal static string MaterialCodeExists {
            get {
                return ResourceManager.GetString("MaterialCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Created Successfully.
        /// </summary>
        internal static string MaterialCreated {
            get {
                return ResourceManager.GetString("MaterialCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaterialMaster Updated Successfully.
        /// </summary>
        internal static string MaterialMasterBatchUpdated {
            get {
                return ResourceManager.GetString("MaterialMasterBatchUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Material.
        /// </summary>
        internal static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material added Succesfully.
        /// </summary>
        internal static string MaterialsAdded {
            get {
                return ResourceManager.GetString("MaterialsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material updated Succesfully.
        /// </summary>
        internal static string MaterialsUpdated {
            get {
                return ResourceManager.GetString("MaterialsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Updated Successfully.
        /// </summary>
        internal static string MaterialUpdated {
            get {
                return ResourceManager.GetString("MaterialUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Created Successfully.
        /// </summary>
        internal static string ModuleCreated {
            get {
                return ResourceManager.GetString("ModuleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name Already Exists.
        /// </summary>
        internal static string ModuleExists {
            get {
                return ResourceManager.GetString("ModuleExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Updated Successfully.
        /// </summary>
        internal static string ModuleUpdated {
            get {
                return ResourceManager.GetString("ModuleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSOMaterial Allocated to Po Succesfully.
        /// </summary>
        internal static string MsoAllocatedtoPO {
            get {
                return ResourceManager.GetString("MsoAllocatedtoPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Sheet Order Approved Successfully.
        /// </summary>
        internal static string MSOApproved {
            get {
                return ResourceManager.GetString("MSOApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Sheet Order Saved Successfully.
        /// </summary>
        internal static string MSOCreated {
            get {
                return ResourceManager.GetString("MSOCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSOHeaderUpdated  Successfully.
        /// </summary>
        internal static string MSOHeaderUpdated {
            get {
                return ResourceManager.GetString("MSOHeaderUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one web module.
        /// </summary>
        internal static string NoModules {
            get {
                return ResourceManager.GetString("NoModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found.
        /// </summary>
        internal static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Association Created Successfully.
        /// </summary>
        internal static string ObjectAssocCreated {
            get {
                return ResourceManager.GetString("ObjectAssocCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Association Updated Successfully.
        /// </summary>
        internal static string ObjectAssocUpdated {
            get {
                return ResourceManager.GetString("ObjectAssocUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Created Successfully.
        /// </summary>
        internal static string ObjectCreated {
            get {
                return ResourceManager.GetString("ObjectCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Updated Successfully.
        /// </summary>
        internal static string ObjectUpdated {
            get {
                return ResourceManager.GetString("ObjectUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Created Successfully.
        /// </summary>
        internal static string PageCreated {
            get {
                return ResourceManager.GetString("PageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageID Already Exists.
        /// </summary>
        internal static string PageIDExists {
            get {
                return ResourceManager.GetString("PageIDExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Updated Successfully.
        /// </summary>
        internal static string PageUpdated {
            get {
                return ResourceManager.GetString("PageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Number Already Exists.
        /// </summary>
        internal static string PermitNumberExists {
            get {
                return ResourceManager.GetString("PermitNumberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Saved Succesfully.
        /// </summary>
        internal static string POAdded {
            get {
                return ResourceManager.GetString("POAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Approved Successfully.
        /// </summary>
        internal static string POApproved {
            get {
                return ResourceManager.GetString("POApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Number Already Exists.
        /// </summary>
        internal static string PONumberExists {
            get {
                return ResourceManager.GetString("PONumberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Rejected Successfully.
        /// </summary>
        internal static string PORejected {
            get {
                return ResourceManager.GetString("PORejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSubmitted Successfully.
        /// </summary>
        internal static string POSubmitted {
            get {
                return ResourceManager.GetString("POSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectification Failed.
        /// </summary>
        internal static string RectifyFail {
            get {
                return ResourceManager.GetString("RectifyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectified Successfully.
        /// </summary>
        internal static string RectifySuccess {
            get {
                return ResourceManager.GetString("RectifySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releasign Materials Succesfully.
        /// </summary>
        internal static string ReleasedMaterials {
            get {
                return ResourceManager.GetString("ReleasedMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Created Successfully.
        /// </summary>
        internal static string RoleCreated {
            get {
                return ResourceManager.GetString("RoleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name Already Exists.
        /// </summary>
        internal static string RoleNameExists {
            get {
                return ResourceManager.GetString("RoleNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Updated Succefully.
        /// </summary>
        internal static string RoleUpdated {
            get {
                return ResourceManager.GetString("RoleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one checkbox.
        /// </summary>
        internal static string SelectMSODetail {
            get {
                return ResourceManager.GetString("SelectMSODetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submited and Saved  the MSODetails to Approval .
        /// </summary>
        internal static string SubmitedMSODetails {
            get {
                return ResourceManager.GetString("SubmitedMSODetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Created Successfully.
        /// </summary>
        internal static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID Already Exists.
        /// </summary>
        internal static string UserIDExists {
            get {
                return ResourceManager.GetString("UserIDExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Updated Successfully.
        /// </summary>
        internal static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Created Successfully.
        /// </summary>
        internal static string WorkCreated {
            get {
                return ResourceManager.GetString("WorkCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Updated Successfully.
        /// </summary>
        internal static string WorkUpdated {
            get {
                return ResourceManager.GetString("WorkUpdated", resourceCulture);
            }
        }
    }
}
