//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace astorWorkDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeZoneMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeZoneMaster()
        {
            this.YardMasters = new HashSet<YardMaster>();
        }
    
        public int TimeZoneID { get; set; }
        public string DisplayName { get; set; }
        public int UTCOffset { get; set; }
    
        public virtual TimeZoneMaster TimeZoneMaster1 { get; set; }
        public virtual TimeZoneMaster TimeZoneMaster2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YardMaster> YardMasters { get; set; }
    }
}
