//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace astorWorkDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class YardMapping
    {
        public int AstorWorkYardID { get; set; }
        public int AstorSafeYardID { get; set; }
        public int AstorTrackYardID { get; set; }
        public string YardName { get; set; }
    }
}
