apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: apigateway
  namespace: qa
  labels:
    app: apigateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: astorwork
        image: astorwork.azurecr.io/api-gateway-2019:1007
        env:
        - name: TENANT_INFO_TBL
          value: TenantInfoQA
        - name: AW_REDIS_CACHE_CONNECTION
          value: astorworkQA.redis.cache.windows.net:6380,password=IQJRK3MrIWzsQkDtDqr43BY2QTv5NpcJKW4bTfSERzc=,ssl=True,abortConnect=False
        - name: IMAGE_CONTAINER
          value: qa-image-repo
                  
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: extensions/v1beta1
kind: Service
apiVersion: v1
metadata:
  name: apigateway
  namespace: qa
spec:
  selector:
    app: apigateway
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443